name: ci

on:
  push:  ## On push to main + Branch protection == Merge
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        run: |
            docker buildx build \
              --push \
              --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
              -t rdogtech/github-runner-pi-base:latest \
              -f Dockerfile-base \
              .
      -
        name: Build and push
        run: |
            docker build \
              -t rdogtech/pi-github-runner:latest .
